package com.webaction.event;

/**
 * Minimal mock of the real Striim {@code com.webaction.event.Event} base class
 * (the real hierarchy
 * is {@code WAEvent extends SourceEvent extends SimpleEvent extends Event extends
 * SizedEvent}). ReferenceOp's compiled bytecode references only {@code WAEvent} and
 * {@code Event} by name (the synthetic covariant bridge method
 * {@code EventProcessor.processEvent(Event)} generated by javac when
 * {@code Processor implements EventProcessor<WAEvent>} declares its single parameter
 * as {@code Event}) — the intermediate classes never appear, so this harness collapses
 * the chain to {@code WAEvent extends Event} directly.
 *
 * <p>
 * This class carries no members: nothing in the operators driven by this harness reads
 * or writes state on {@code Event} itself — it exists purely so the class name resolves
 * (bytecode verification of the bridge method's stack map frames requires it) and so
 * {@code WAEvent} satisfies the {@code EventProcessor<E extends Event>} bound.
 */
public class Event {
}
