__version__ = "0.1.0"

# Build-time provenance (U1.4 Step 4). livetest/_provenance.py is GENERATED by
# _build_backend.py at build time and git-ignored (never committed); a bare
# source checkout that was never built has no such file, so import it defensively
# and report a checkout with unknown git state rather than raising. Exposed as a
# dict so run-gold.sh's released-consumer gate (livetest._release_gate) can read
# GIT_SHA / DIRTY / BUILT_FROM off the installed distribution.
try:
    from livetest import _provenance as _prov

    __provenance__ = {
        "VERSION": getattr(_prov, "VERSION", __version__),
        "GIT_SHA": getattr(_prov, "GIT_SHA", None),
        "DIRTY": getattr(_prov, "DIRTY", None),
        "BUILT_FROM": getattr(_prov, "BUILT_FROM", "checkout"),
    }
    __version__ = __provenance__["VERSION"]
except Exception:
    __provenance__ = {
        "VERSION": __version__,
        "GIT_SHA": None,
        "DIRTY": None,
        "BUILT_FROM": "checkout",
    }
